site_name: 'Example Documentation'
repo_url: https://github.com/backstage/backstage
edit_uri: edit/master/plugins/techdocs-backend/examples/documented-component/docs

nav:
  - Home: index.md
  - Endpoints: endpoints.md
  - 'CI pipeline': ci-pipeline.md

plugins:
  - techdocs-core
