site_name: 'Sample API documentation'
repo_url: https://github.com/poshtarenko/backstage-techdocs
edit_uri: edit/docs

nav:
  - Home: index.md
  - Endpoints: endpoints.md
  - 'CI pipeline': ci-pipeline.md

plugins:
  - techdocs-core
