site_name: 'Sample API documentation'
repo_url: https://github.com/username/repo-name
edit_uri: edit/main/docs

nav:
  - Home: index.md
  - Endpoints: endpoints.md
  - 'CI pipeline': ci-pipeline.md

plugins:
  - techdocs-core
